server:
  port: 5005


spring:
  kafka:
    consumer:
      bootstrap-servers: kafka1:9092, kafka2:9092, kafka0:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka1:9092, kafka2:9092, kafka0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  boot:
    admin:
      client:
        url: http://localhost:5005/admin
      context-path: /admin


management:
  endpoints:
    web:
      exposure:
        include: "*"
